"""initial_schema

Revision ID: c950fc1ba889
Revises: 
Create Date: 2026-07-10 20:56:34.204494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c950fc1ba889'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('width_meters', sa.Float(), nullable=True),
    sa.Column('depth_meters', sa.Float(), nullable=True),
    sa.Column('height_meters', sa.Float(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('scale_factor', sa.Float(), nullable=True),
    sa.Column('camera_matrix', sa.JSON(), nullable=True),
    sa.Column('dist_coeffs', sa.JSON(), nullable=True),
    sa.Column('floor_plan_url', sa.String(length=500), nullable=True),
    sa.Column('point_cloud_url', sa.String(length=500), nullable=True),
    sa.Column('selected_products', sa.JSON(), nullable=True),
    sa.Column('wall_color', sa.String(length=50), nullable=True),
    sa.Column('floor_type', sa.String(length=100), nullable=True),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Float(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('frames_extracted', sa.Integer(), nullable=True),
    sa.Column('markers_detected', sa.Integer(), nullable=True),
    sa.Column('scale_factor', sa.Float(), nullable=True),
    sa.Column('camera_matrix', sa.JSON(), nullable=True),
    sa.Column('dist_coeffs', sa.JSON(), nullable=True),
    sa.Column('control_points', sa.JSON(), nullable=True),
    sa.Column('output_dir', sa.String(length=500), nullable=True),
    sa.Column('point_cloud_path', sa.String(length=500), nullable=True),
    sa.Column('floor_plan_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('measurement_type', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('value_meters', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('point1', sa.JSON(), nullable=True),
    sa.Column('point2', sa.JSON(), nullable=True),
    sa.Column('reference_object', sa.String(length=100), nullable=True),
    sa.Column('reference_value', sa.Float(), nullable=True),
    sa.Column('width_meters', sa.Float(), nullable=True),
    sa.Column('height_meters', sa.Float(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    op.drop_table('videos')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###